/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetsir.interfaces;

import java.awt.GridLayout;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import projetsir.Parametres;
import projetsir.bd_globale;

/**
 *
 * @author yv965015
 */
public class Verif_Frag_Verticale extends javax.swing.JFrame
{
    String table;
    String[] cleP,attS;
    int[][] frag;
    int[][] site_att;
    int nbS, nbA;
    bd_globale bd;
    private Parametres parametres;
    /**
     * Creates new form Verif_Frag_Verticale
     */
    public Verif_Frag_Verticale(String table, int[][] frag)
    {
        initComponents();
        this.nom_table.setText(table);
        this.table=table;
        this.frag=frag;
        //1er fragment,2° attribut, si 1 là
        bd =new bd_globale();
        cleP=bd.get_cles_primaires(table);
        attS=bd.get_attributs_non_primaires(table);
        GridLayout gd=new GridLayout(frag.length+1,frag[0].length+1);
        this.pan_frag.setLayout(gd);
        for(int i=0;i<frag.length+1;i++)
        {
            if(i==0)
            {

                for(int j=0;j<attS.length+cleP.length+1;j++)
                {
                    if(j==0)
                    {
                        JLabel nomA=new JLabel();
                        nomA.setText("");
                        pan_frag.add(nomA);
                    }
                    else
                    {
                        if(j<cleP.length+1)
                        {
                            JLabel nomA=new JLabel();
                            nomA.setText(""+cleP[j-1]);
                            pan_frag.add(nomA); 
                        }
                        else
                        {
                            JLabel nomA=new JLabel();
                            nomA.setText(""+attS[j-(cleP.length+1)]);
                            pan_frag.add(nomA);
                        }
                    }
                }
            }
            else
            {
                 for(int j=0;j<attS.length+cleP.length+1;j++)
                {
                    if(j==0)
                    {
                        JLabel nomF=new JLabel();
                        nomF.setText("Fragment "+i);
                        pan_frag.add(nomF); 
                    }
                    else
                    {
                        if(j<cleP.length+1)
                        {
                            JCheckBox ch=new JCheckBox();
                            ch.setName("cleP");
                            ch.setEnabled(false);
                            ch.setSelected(true);
                            this.pan_frag.add(ch);
                        }
                        else
                        {
                            JCheckBox ch=new JCheckBox();
                            ch.setName(""+i+"_"+j);
                            if(frag[i-1][j-(cleP.length+1)]!=-1)
                            {
                                ch.setSelected(true);
                            }
                            this.pan_frag.add(ch);
                        }
                    }
                }
            }
        }
        this.nom_table.setText(table);     
    }
    
    private void construction_fichier(String chemin_schemas, int[][] fragmentation)
    {
        String contenu = "";
        contenu += this.construction_fragmentation(fragmentation);

        //Ecriture sur tablefrag.json
        FileWriter out = null;
        try
        {
            out = new FileWriter(new File(chemin_schemas));
            out.write(contenu);
            out.close();
            System.out.println("Fichier créé.");
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }
    }
    
    private String construction_fragmentation(int[][] fragmentation)
    {
        String s = "";
        String[] attributs = this.bd.get_liste_attributs_table(this.table);
        for(int i=0; i<attributs.length; i++)
        {
            s += attributs[i];
            if(i<attributs.length-1)
                s += " ";
        }
        s += "\nverticale\n";
        for(int i=0; i<fragmentation.length; i++)
        {
            for(int j=0; j<fragmentation[0].length; j++)
            {
                if(fragmentation[i][j]==1)
                    s += "1";
                else
                    s += "0";
                if(j<fragmentation[0].length-1)
                    s += " ";
            }
            s += "\n";
        }
        return s;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pan_principal = new javax.swing.JPanel();
        nom_table = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pan_frag = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pan_buttons = new javax.swing.JPanel();
        annuler_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        valider_button_frag = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pan_principal.setLayout(new java.awt.BorderLayout());

        nom_table.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pan_principal.add(nom_table, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout pan_fragLayout = new javax.swing.GroupLayout(pan_frag);
        pan_frag.setLayout(pan_fragLayout);
        pan_fragLayout.setHorizontalGroup(
            pan_fragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        pan_fragLayout.setVerticalGroup(
            pan_fragLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jPanel1.add(pan_frag);

        pan_principal.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        pan_buttons.setLayout(new java.awt.GridLayout(1, 0));

        annuler_button.setText("Annuler");
        annuler_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                annuler_buttonActionPerformed(evt);
            }
        });
        pan_buttons.add(annuler_button);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        valider_button_frag.setText("Valider la fragmentation");
        valider_button_frag.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                valider_button_fragActionPerformed(evt);
            }
        });
        jPanel3.add(valider_button_frag);

        pan_buttons.add(jPanel3);

        jPanel2.add(pan_buttons);

        pan_principal.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pan_principal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annuler_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_annuler_buttonActionPerformed
    {//GEN-HEADEREND:event_annuler_buttonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_annuler_buttonActionPerformed

    private void valider_button_fragActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_valider_button_fragActionPerformed
    {//GEN-HEADEREND:event_valider_button_fragActionPerformed
        //int[][] distri=new int[frag.length][nbS];
        int u=0;
        int k=0;
        boolean flag=false;
        boolean flag2=true;
        nbA=bd.get_nb_attributs(table);
        int[][] mat_frag=new int[frag.length][nbA];
        String[] att=bd.get_liste_attributs_table(table);
        u=0;
        k=0;
        for(int i=nbA+2;i<(nbA+1)*(frag.length+1);i++)
        {
            if(this.pan_frag.getComponent(i).getClass()==JCheckBox.class)
            {
                JCheckBox jb=(JCheckBox)this.pan_frag.getComponent(i);
                if(jb.isSelected())
                {
                    mat_frag[u][k]=1;
                }
                else
                    mat_frag[u][k]=0;
                k++;
                if(k>=nbA)
                {
                    u++;
                    k=0;
                }
            }
        } 
       
        for (int f=0; f<nbA;f++)
        {
            flag=false;
            for (int s=0; s<mat_frag.length;s++)
            {
                if (mat_frag[s][f]==1)
                {   
                    flag=true;
                }     
            }
            if(!flag)
            {
                flag2=false;
            }
        }
        
        if(flag2)
        {
            parametres = new Parametres();
            //this.construction_fichier("src/fragmentation_temporaire/"+table);
            this.construction_fichier("src/fragments/"+table, mat_frag);
            this.setVisible(false);
        }
        else
        {
            String msg="merci de bien distribuer les attributs";
            String title="Erreur de distribution"; {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                msg,
                title,
                javax.swing.JOptionPane.WARNING_MESSAGE);
                }
        }
    }//GEN-LAST:event_valider_button_fragActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Verif_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Verif_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Verif_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Verif_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nom_table;
    private javax.swing.JPanel pan_buttons;
    private javax.swing.JPanel pan_frag;
    private javax.swing.JPanel pan_principal;
    private javax.swing.JButton valider_button_frag;
    // End of variables declaration//GEN-END:variables
}
