/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetsir;

import java.awt.GridLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author yv965015
 */
public class Confirmation_Frag_Verticale extends javax.swing.JFrame
{

    /**
     * Creates new form Confirmation_Frag_Verticale
     */
    public Confirmation_Frag_Verticale(String table,int[][] frag)
    {
        initComponents();
        this.nom_table.setText(table);
        //1er fragment,2° attribut, si 1 là
        //bd_globale bd=new bd_globale();
        Parametres param = new Parametres();
        int nbS = param.get_nb_serveurs();
        GridLayout gd=new GridLayout(frag.length+1,nbS+1);
        this.pan_affichage.setLayout(gd);
        for(int i=0;i<frag.length+1;i++)
        {
            if(i==0)
            {

                for(int j=0;j<nbS+1;j++)
                {
                    if(j==0)
                    {
                        JLabel nomS=new JLabel();
                        nomS.setText("");
                        pan_affichage.add(nomS);
                    }
                    else
                    {
                        JLabel nomS=new JLabel();
                        nomS.setText("Site :"+param.get_num_serveur(j));
                        pan_affichage.add(nomS);
                    }
                }
            }
            else
            {
                 for(int j=0;j<nbS+1;j++)
                {
                    if(j==0)
                    {
                        JLabel nomF=new JLabel();
                        nomF.setText("Fragment "+i);
                        pan_affichage.add(nomF); 
                    }
                    else
                    {
                        JCheckBox ch=new JCheckBox();
                        ch.setName(""+i+"_"+j);
                        this.pan_affichage.add(ch);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pan_principal = new javax.swing.JPanel();
        pan_button = new javax.swing.JPanel();
        annuler_button = new javax.swing.JButton();
        valider_button = new javax.swing.JButton();
        pan_affichage = new javax.swing.JPanel();
        nom_table = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        pan_principal.setLayout(new java.awt.BorderLayout());

        pan_button.setLayout(new java.awt.GridLayout());

        annuler_button.setText("Annuler");
        pan_button.add(annuler_button);

        valider_button.setText("Valider");
        pan_button.add(valider_button);

        pan_principal.add(pan_button, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout pan_affichageLayout = new javax.swing.GroupLayout(pan_affichage);
        pan_affichage.setLayout(pan_affichageLayout);
        pan_affichageLayout.setHorizontalGroup(
            pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pan_affichageLayout.setVerticalGroup(
            pan_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pan_principal.add(pan_affichage, java.awt.BorderLayout.CENTER);

        nom_table.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pan_principal.add(nom_table, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pan_principal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Confirmation_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Confirmation_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Confirmation_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Confirmation_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler_button;
    private javax.swing.JLabel nom_table;
    private javax.swing.JPanel pan_affichage;
    private javax.swing.JPanel pan_button;
    private javax.swing.JPanel pan_principal;
    private javax.swing.JButton valider_button;
    // End of variables declaration//GEN-END:variables
}
