/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetsir;

import java.awt.GridLayout;
import javax.swing.*;

/**
 *
 * @author yv965015
 */
public class DLG_Frag_Verticale extends javax.swing.JFrame {

    /**
     * Creates new form DLG_Frag_Verticale
     */
    public DLG_Frag_Verticale(String table) {
        JOptionPane jop = new JOptionPane();
        String nbQ="";
        String message="Nombre de requêtes ?";
        int nbR=0;
        while(!nbQ.matches("^\\d+$")||nbQ.matches(""))
        {    
            nbQ = jop.showInputDialog(null, message, JOptionPane.QUESTION_MESSAGE);
            if(nbQ.matches("^\\d+$"))
            {
                nbR=Integer.parseInt(nbQ);
            }
            else
                message="Nombre de requêtes en nombre positif ? ";
        }
        Parametres param=new Parametres();
        int nbS=param.get_nb_serveurs();
        bd_globale bdg=new bd_globale();
        String[] liste_att=bdg.get_liste_attributs_table(table);
        int nbA=liste_att.length;
        initComponents();
        Pan_Dis.setLayout(new GridLayout(nbR,nbS));
        Pan_Ut.setLayout(new GridLayout(nbR,nbA));
        this.creationMatDis(nbR, nbS);
        this.creationMatUt(nbR, nbA);
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pan_Dis = new javax.swing.JPanel();
        Pan_Ut = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout Pan_DisLayout = new javax.swing.GroupLayout(Pan_Dis);
        Pan_Dis.setLayout(Pan_DisLayout);
        Pan_DisLayout.setHorizontalGroup(
            Pan_DisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        Pan_DisLayout.setVerticalGroup(
            Pan_DisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(Pan_Dis);

        Pan_Ut.setLayout(new java.awt.GridLayout());
        getContentPane().add(Pan_Ut);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DLG_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DLG_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DLG_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DLG_Frag_Verticale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
    void creationMatDis(int nbR,int nbS)
    {
        for(int i=0;i<nbR;i++)
        {
            for(int j=0;j<nbS;j++)
            {
                SpinnerModel model = new SpinnerNumberModel();
                JSpinner spin=new JSpinner(model);
                Pan_Dis.add(spin);
            }
        }
        
        
    }
    void creationMatUt(int nbR,int nbA)
    {
        for(int i=0;i<nbR;i++)
        {
            for(int j=0;j<nbA;j++)
            {
                JCheckBox ch=new JCheckBox();
                Pan_Ut.add(ch);
            }
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pan_Dis;
    private javax.swing.JPanel Pan_Ut;
    // End of variables declaration//GEN-END:variables
}
