/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetsir;

import java.awt.GridLayout;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author ag092850
 */
public class Dlg_parametres extends javax.swing.JFrame {

    private Parametres parametres;
    private int nb_serveurs;
    private List<Integer> num_serveurs;
    
    public Dlg_parametres() {
        initComponents();
        this.initialisation();
    }

    private void initialisation()
    {
        this.parametres = new Parametres();
        this.NumLocal.setValue(this.parametres.get_num_serveur_local());
        this.PortLocal.setText(""+this.parametres.get_port_serveur_local());
        this.LoginBD.setText(this.parametres.getBD_login());
        this.MdpBD.setText(this.parametres.getBD_mdp());
        this.nb_serveurs = this.parametres.get_nb_serveurs();
        this.num_serveurs = new ArrayList<>();
        for(int i=0; i<this.nb_serveurs; i++)
        {
            this.num_serveurs.add(this.parametres.get_num_serveur(i));
        }
        this.remplissageServeurs();
    }
    
    private void remplissageServeurs()
    {
        this.Serveurs.removeAll();
        this.Serveurs.setLayout(new GridLayout(this.nb_serveurs-1, 3));
        for(int i=0; i<this.nb_serveurs; i++)
        {
            if(this.num_serveurs.get(i)!=this.parametres.get_num_serveur_local())
            {
                //Ne pas ajouter le serveur si c'est le local
                JLabel jl = new JLabel();
                jl.setText("Serveur "+(i+1)+" : ");
                SpinnerModel model = new SpinnerNumberModel();
                JSpinner js = new JSpinner(model);
                js.setValue(this.num_serveurs.get(i));
                js.setName("js"+i);
                JButton jb = new JButton();
                jb.setText("Supprimer");
                jb.setName("jb"+i);
                //Ajout du listener
                jb.addActionListener(new java.awt.event.ActionListener() 
                {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        supprimerServeur(evt);
                    }
                });
                this.Serveurs.add(jl);
                this.Serveurs.add(js);
                this.Serveurs.add(jb);
            }
        }
    }
    
    private void supprimerServeur(java.awt.event.ActionEvent evt)
    {
        JButton jb = (JButton)evt.getSource();
        int num = Integer.parseInt(jb.getName().split("jb")[0]);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NumLocal = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        PortLocal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LoginBD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MdpBD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AjoutServeur = new javax.swing.JButton();
        Serveurs = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("Numéro du serveur :");
        jPanel2.add(jLabel1);
        jPanel2.add(NumLocal);

        jLabel2.setText("Port du serveur :");
        jPanel2.add(jLabel2);
        jPanel2.add(PortLocal);

        jLabel3.setText("Login da la BD :");
        jPanel2.add(jLabel3);
        jPanel2.add(LoginBD);

        jLabel4.setText("Mot de passe de la BD :");
        jPanel2.add(jLabel4);
        jPanel2.add(MdpBD);

        jLabel5.setText("Serveurs externes :");
        jPanel2.add(jLabel5);

        AjoutServeur.setText("Ajouter un serveur");
        AjoutServeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutServeurActionPerformed(evt);
            }
        });
        jPanel2.add(AjoutServeur);

        jPanel1.add(jPanel2);

        Serveurs.setLayout(new java.awt.GridLayout(1, 2));
        jPanel1.add(Serveurs);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel3.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel3.add(Valider);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValiderActionPerformed

    private void AjoutServeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutServeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjoutServeurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dlg_parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dlg_parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dlg_parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dlg_parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dlg_parametres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutServeur;
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField LoginBD;
    private javax.swing.JTextField MdpBD;
    private javax.swing.JSpinner NumLocal;
    private javax.swing.JTextField PortLocal;
    private javax.swing.JPanel Serveurs;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
